#
# Options that are set by GitHub and cannot be changed
#

lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
    noscript: false
kramdown:
    math_engine: mathjax
    syntax_highlighter: rouge


#
# Options with defaults set by GitHub that can be changed
#

encoding: UTF-8
kramdown:
    input: GFM
    hard_wrap: false
future: true
jailed: false
theme: jekyll-theme-primer
gfm_quirks: paragraph_end


#
# Other options
#

exclude: [CNAME, Gemfile, Gemfile.lock, README.markdown, vendor]
include: [_sources, _static]  # For Sphinx-generated docs
permalink: pretty
timezone: America/New_York


#
# Custom site data
#

url: https://mworks.github.io
authors:
  - id: cstawarz
    fullname: Christopher Stawarz
    url: https://github.com/cstawarz

  - id: davidcox
    fullname: David Cox
    url: https://github.com/davidcox
